1. 
 public class MyClass {
    static String str = "a";
 
    public static void main(String[] args) {
           new MyClass().method1();
           System.out.println(str);
    }
 
    void method1() {
           try {
                  method2();
           } catch (Exception e) {
                  str += "b";
           }
    }
 
    void method2() throws Exception {
           try{
                  method3();
                  str += "c";
           }catch(Exception e){
                  throw new Exception();
           }finally{
                  str += "d";
           }
           method3();
           str += "e";
    }
 
    void method3() throws Exception {
           throw new Exception();
    }
}

// abd

2. 
 public static void main(String[] args) {
           m(); //call recursive method m()
           System.out.println("Code after exception handling");
    }
    
    static void m() {
           try {
                  m();
           } catch (StackOverflowError e) {
                  e.printStackTrace();
           }
    }

// Stackoverflow error 

3. 
   try{
                  int i=10/0;
           }catch(Exception e){
                  System.out.println("Exception handled  properly in catch block");
           }          
           System.out.println("Code after exception handling");

Exception handled  properly
Code after exception handling

4. 
   try{
         int i=10/0; //will throw ArithmeticException
      }catch(ArithmeticException e){
         System.out.println("ArithmeticException handled in catch block");
      }finally{
         System.out.println("finally block executed");              
      }
 
      System.out.println("code after try-catch-finally block");


//
 ArithmeticException handled in catch block
finally block executed
code after try-catch-finally block

5. 
 try{
                  System.out.println("in try block");
                  System.exit(0);
           }finally{
                  System.out.println("finally block executed");              
           }

// in try block
